"""The published Table 8 baseline, one entry per live cell.

Generated by joining docs/sources/table8_baseline.csv onto data/registry/ on the
table8_label of each dimension. Nothing here is transcribed by hand.

Two conversions happen on read, here and nowhere else:

  * a percent-format metric is DIVIDED by 100, because the CSV is the one source
    that arrives in display units while everything under data/ stores a fraction.
    See docs/DATA_CONTRACT.md, "Percent storage - the single authoritative rule".
  * a published sentinel becomes a one-sided Bound, never a value with a display
    override. The paper thresholded the underlying number away, so it does not
    exist in any source we have.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from decimal import Decimal
from enum import StrEnum
from functools import cache
from pathlib import Path

from tools import registry as reg

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "docs" / "sources" / "table8_baseline.csv"
BASELINE_PATH = ROOT / "data" / "baseline.json"

PAPER = "paper"
PUBLISHED = "published"
DEGENERATE = "degenerate"

_PERCENT_SCALE = Decimal(100)


class BoundKind(StrEnum):
    """The four shapes a published baseline can take.

    An enum rather than a `Literal` alias because this value crosses a JSON
    boundary. `data/baseline.json` stores it as text, and reading it back into a
    `Literal` yields a bare `str` that nothing validates at runtime, so a drifted
    or corrupted kind degrades into a silently-False `==`. `BoundKind(raw)`
    raises at the parse boundary instead.

    That distinction is load-bearing rather than stylistic: the ABSENT check is
    what stops a comparison being drawn against a degenerate 0/0 baseline, and a
    silent False there awards `beats_baseline` against a baseline that was never
    measured. StrEnum is a `str` subclass, so the emitted JSON is unchanged.
    """

    EXACT = "exact"
    GREATER_THAN = "greater_than"
    LESS_THAN = "less_than"
    ABSENT = "absent"


@dataclass(frozen=True, slots=True)
class Bound:
    """What the paper published about one cell's baseline, as a one-sided fact.

    Phase 4's ranking consumes this, so the shape is a contract rather than an
    implementation detail.

    EXACT        `value` is the number. Every comparison is decidable.
    GREATER_THAN the true value is strictly ABOVE `value`. Published as
                 "> 10000 %".
    LESS_THAN    the true value is strictly BELOW `value`. Published as "< -1".
    ABSENT       no baseline was ever measured; `value` is None. This is the 0/0
                 case, not a value of zero, and nothing may be scored as beating
                 it.

    `value` is None if and only if `kind` is ABSENT.

    A sentinel always points AWAY from the good direction: the baseline is known
    to be worse than the bound, never better. So GREATER_THAN only ever appears
    on a lower-is-better metric and LESS_THAN only on a higher-is-better one,
    and a submission on the defined side of the threshold is a decidable win:

      greater_than, lower-is-better  -> a submission at or below `value` wins;
                                        anything above it is `no_comparison`
      less_than, higher-is-better    -> a submission at or above `value` wins;
                                        anything below it is `no_comparison`
      absent                         -> always `no_comparison`

    That invariant is asserted in tools/checks/baseline.py rather than assumed.
    """

    kind: BoundKind
    value: float | None


def parse_bound(raw: str, *, percent: bool) -> Bound:
    """Turn one Table 8 cell into a Bound.

    `percent` comes from the metric registry, never from the presence of a "%" in
    the string. The suffix is a formatting artifact of the table; the registry is
    the rule, and the two must not be allowed to drift.

    Scaling is decimal, not binary. The CSV holds decimal strings, so dividing as
    Decimal and crossing to float once keeps the emitted JSON free of artifacts
    like 0.12429999999999999.
    """
    text = raw.strip()
    if not text:
        raise ValueError("empty baseline value: a cell with no published number")

    kind = BoundKind.EXACT
    if text.startswith(">"):
        kind, text = BoundKind.GREATER_THAN, text[1:]
    elif text.startswith("<"):
        kind, text = BoundKind.LESS_THAN, text[1:]

    number = Decimal(text.strip().removesuffix("%").strip().replace(",", ""))
    if percent:
        number /= _PERCENT_SCALE
    return Bound(kind=kind, value=float(number))


CellKey = tuple[str, str, str, str]


@dataclass(frozen=True, slots=True)
class Baseline:
    """One live cell's published baseline."""

    task: str
    metric: str
    pdk: str
    stage: str
    baseline_state: str
    bound: Bound
    source: str
    src_line: int

    @property
    def key(self) -> CellKey:
        return (self.task, self.metric, self.pdk, self.stage)


LabelKey = tuple[str, str, str, str]


@cache
def _csv_index() -> dict[LabelKey, dict[str, str]]:
    """The CSV, indexed on (task, metric, stage, pdk) table8 labels."""
    with CSV_PATH.open(encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    index: dict[LabelKey, dict[str, str]] = {}
    for row in rows:
        key = (row["task"], row["metric"], row["stage_transition"], row["pdk"])
        if key in index:
            raise ValueError(f"duplicate Table 8 row for {key}")
        index[key] = row
    return index


@cache
def _label_key_index() -> dict[CellKey, LabelKey]:
    """Cell ids to the labels that join them onto the CSV."""
    task_label = {t.id: t.table8_label for t in reg.tasks()}
    metric_label = {m.id: m.table8_label for m in reg.metrics()}
    stage_label = {s.id: s.table8_label for s in reg.stages()}
    pdk_label = {p.id: p.table8_label for p in reg.pdks()}
    return {
        (task_id, metric_id, pdk_id, stage_id): (
            task_label[task_id],
            metric_label[metric_id],
            stage_label[stage_id],
            pdk_label[pdk_id],
        )
        for task_id, metric_id, pdk_id, stage_id in reg.live_cells()
    }


@cache
def published_sentinel_keys() -> frozenset[CellKey]:
    """Cells the paper published as a threshold rather than a number.

    Derived by scanning the raw value strings, deliberately by a different route
    than parse_bound takes. A sentinel silently demoted to an exact value is then
    caught by disagreement rather than confirmed by a shared reading.
    """
    rows = _csv_index()
    return frozenset(
        cell_key
        for cell_key, label_key in _label_key_index().items()
        if rows[label_key]["value"].strip().startswith((">", "<"))
    )


def build() -> tuple[Baseline, ...]:
    """One Baseline per live cell, in registry order.

    Driven from reg.live_cells() rather than from the CSV, so the emitted key set
    is the live set by construction and a published cell the table does not carry
    raises instead of quietly vanishing.
    """
    rows = _csv_index()
    entries: list[Baseline] = []

    for cell_key, label_key in _label_key_index().items():
        task_id, metric_id, pdk_id, stage_id = cell_key
        try:
            row = rows[label_key]
        except KeyError:
            raise KeyError(f"no Table 8 row for {label_key}") from None

        if row["kind"] == "VOID":
            raise ValueError(
                f"the registry says this cell is live, Table 8 says VOID: {cell_key}"
            )

        degenerate = reg.is_degenerate(task_id, metric_id, stage_id)
        if degenerate != (row["kind"] == "DEGENERATE"):
            raise ValueError(
                f"degeneracy disagrees between the registry and Table 8: {cell_key}"
            )

        bound = (
            Bound(kind=BoundKind.ABSENT, value=None)
            if degenerate
            else parse_bound(row["value"], percent=reg.metric(metric_id).percent)
        )
        entries.append(
            Baseline(
                task=task_id,
                metric=metric_id,
                pdk=pdk_id,
                stage=stage_id,
                baseline_state=DEGENERATE if degenerate else PUBLISHED,
                bound=bound,
                source=PAPER,
                src_line=int(row["src_line"]),
            )
        )
    return tuple(entries)


def to_json(entries: tuple[Baseline, ...]) -> str:
    """Serialize deterministically.

    Order is registry order, taken from build(), so the file reads in the same
    sequence as the matrix and a diff stays local to what actually changed.
    """
    payload = {
        "generated_from": CSV_PATH.relative_to(ROOT).as_posix(),
        "cells": [
            {
                "task": entry.task,
                "metric": entry.metric,
                "pdk": entry.pdk,
                "stage": entry.stage,
                "baseline_state": entry.baseline_state,
                "bound": {"kind": entry.bound.kind, "value": entry.bound.value},
                "source": entry.source,
                "src_line": entry.src_line,
            }
            for entry in entries
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    """Regenerate data/baseline.json. Entry point for `eda-baseline`."""
    entries = build()
    BASELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
    BASELINE_PATH.write_text(to_json(entries), encoding="utf-8")
    print(
        f"baseline: wrote {len(entries)} cells to "
        f"{BASELINE_PATH.relative_to(ROOT).as_posix()}"
    )
    return 0
