"""The published Table 8 baseline, one entry per live cell.

Generated by joining docs/sources/table8_baseline.csv onto data/registry/ on the
table8_label of each dimension. Nothing here is transcribed by hand.

Two conversions happen on read, here and nowhere else:

  * a percent-format metric is DIVIDED by 100, because the CSV is the one source
    that arrives in display units while everything under data/ stores a fraction.
    See docs/DATA_CONTRACT.md, "Percent storage - the single authoritative rule".
  * a published sentinel becomes a one-sided Bound, never a value with a display
    override. The paper thresholded the underlying number away, so it does not
    exist in any source we have.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from enum import StrEnum
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "docs" / "sources" / "table8_baseline.csv"
BASELINE_PATH = ROOT / "data" / "baseline.json"

PAPER = "paper"
PUBLISHED = "published"
DEGENERATE = "degenerate"

_PERCENT_SCALE = Decimal(100)


class BoundKind(StrEnum):
    """The four shapes a published baseline can take.

    An enum rather than a `Literal` alias because this value crosses a JSON
    boundary. `data/baseline.json` stores it as text, and reading it back into a
    `Literal` yields a bare `str` that nothing validates at runtime, so a drifted
    or corrupted kind degrades into a silently-False `==`. `BoundKind(raw)`
    raises at the parse boundary instead.

    That distinction is load-bearing rather than stylistic: the ABSENT check is
    what stops a comparison being drawn against a degenerate 0/0 baseline, and a
    silent False there awards `beats_baseline` against a baseline that was never
    measured. StrEnum is a `str` subclass, so the emitted JSON is unchanged.
    """

    EXACT = "exact"
    GREATER_THAN = "greater_than"
    LESS_THAN = "less_than"
    ABSENT = "absent"


@dataclass(frozen=True, slots=True)
class Bound:
    """What the paper published about one cell's baseline, as a one-sided fact.

    Phase 4's ranking consumes this, so the shape is a contract rather than an
    implementation detail.

    EXACT        `value` is the number. Every comparison is decidable.
    GREATER_THAN the true value is strictly ABOVE `value`. Published as
                 "> 10000 %".
    LESS_THAN    the true value is strictly BELOW `value`. Published as "< -1".
    ABSENT       no baseline was ever measured; `value` is None. This is the 0/0
                 case, not a value of zero, and nothing may be scored as beating
                 it.

    `value` is None if and only if `kind` is ABSENT.

    A sentinel always points AWAY from the good direction: the baseline is known
    to be worse than the bound, never better. So GREATER_THAN only ever appears
    on a lower-is-better metric and LESS_THAN only on a higher-is-better one,
    and a submission on the defined side of the threshold is a decidable win:

      greater_than, lower-is-better  -> a submission at or below `value` wins;
                                        anything above it is `no_comparison`
      less_than, higher-is-better    -> a submission at or above `value` wins;
                                        anything below it is `no_comparison`
      absent                         -> always `no_comparison`

    That invariant is asserted in tools/checks/baseline.py rather than assumed.
    """

    kind: BoundKind
    value: float | None


def parse_bound(raw: str, *, percent: bool) -> Bound:
    """Turn one Table 8 cell into a Bound.

    `percent` comes from the metric registry, never from the presence of a "%" in
    the string. The suffix is a formatting artifact of the table; the registry is
    the rule, and the two must not be allowed to drift.

    Scaling is decimal, not binary. The CSV holds decimal strings, so dividing as
    Decimal and crossing to float once keeps the emitted JSON free of artifacts
    like 0.12429999999999999.
    """
    text = raw.strip()
    if not text:
        raise ValueError("empty baseline value: a cell with no published number")

    kind = BoundKind.EXACT
    if text.startswith(">"):
        kind, text = BoundKind.GREATER_THAN, text[1:]
    elif text.startswith("<"):
        kind, text = BoundKind.LESS_THAN, text[1:]

    number = Decimal(text.strip().removesuffix("%").strip().replace(",", ""))
    if percent:
        number /= _PERCENT_SCALE
    return Bound(kind=kind, value=float(number))
